### ISSUE TITLE
Support nightscout authentication, AUTH_DEFAULT_ROLES=denied configuration

### ISSUE THREAD

**Issue by becksen** [rahim/nightwear#28]
I've downloaded nightwar form PlayStore. Configuring watchface I got the error "Invalid URL" although the URL is abolutely correct. Have confirmed it multiple times.

My NS URL is secured via token or secred. What is the correct syntax for the URL?

XDrip: <token>@domain.herokuapp.com
Nightguard: domain.herokuapp.com?=token

Please let me know what the correct syntax is for nightwear.

Thanks.

**Comment by rahim** [comment]
Nightwear expects the default `AUTH_DEFAULT_ROLES=readonly` nightscout config, there's currently no support for auth to support `AUTH_DEFAULT_ROLES=denied` (described in https://github.com/nightscout/cgm-remote-monitor#features)

It feels like an entirely sensible thing to add, but this is actually the first request I've had for it, it seems that most users run with that default.

**Comment by butzifutz** [comment]
Hi, I can upvote the request. Support for tokens would be really nessesary.  I donn't want the cgm data to be readably to the world.

**Comment by rahim** [comment]
Nightscout's own [secure your site documentation](https://nightscout.github.io/nightscout/security/) show the site URL with token as
```
https://yoursitename.herokuapp.com/?token=school-a595d5f0aeff64c0
```
Because we're doing all input on a watch we have a fairly funky approach to entering the URL (to try to minimise pain) split across multiple UI controls, constructing the URL from various pieces after the fact. We'll need a new field for the token.

`BloodGlucoseService` will need to know to append the token as query param to all requests (or if it's supported it would be preferable to send as an HTTP header, but that will require some investigation).

**Comment by rahim** [comment]
Reading a little further, there are separate [docs for API authentication](https://github.com/nightscout/cgm-remote-monitor/wiki/API-v1-Security), which suggest we should be able to send the token in a custom `API-SECRET` HTTP header.

**Comment by Arakon** [comment]
I'd also greatly appreciate this feature.
Also, it seems that the filter blocks other URLs.. I self-host nightscout, since heroku is moving to paid-only, and it seems to refuse to accept my personal URL.. although this may be down to not getting access due to needing the token.

**Comment by rahim** [comment]
Hi @Loquacity - the experience is a bit awkward but you should be able to use arbitrary URLs with the existing version of the Nightwear. I think in the dropdown you'll need to switch "Heroku" to "[Other]" and then where you previously had `mysite` in the text field you instead need `mysite.randomthing.com` (which will be painful to enter on the watch, but should be possible).

I've started work on supporting the API key for the issue here and as part of that work have added a couple of the more common extensions for heroku alternatives like `fly.dev`.

**Comment by rahim** [comment]
I seem to have acknowledged @Arakon's message, but don't remember doing so. Sorry! 

That sounds buggy in a way that I've not observed and sounds like @Loquacity is reporting the same problem. I'll open another issue.

**Comment by Loquacity** [comment]
> Hi @Loquacity - the experience is a bit awkward but you should be able to use arbitrary URLs with the existing version of the Nightwear. I think in the dropdown you'll need to switch "Heroku" to "[Other]" and then where you previously had `mysite` in the text field you instead need `mysite.randomthing.com` (which will be painful to enter on the watch, but should be possible).
> 

Thanks for getting back to me, that's exactly what I've done, and I'm getting an "invalid URL" response. When I include an API token, it accepts the URL (as `other`), but then it appends the herokuapp.com regardless, which then means it can't resolve it (as @Arakon [reported above](https://github.com/rahim/nightwear/issues/28#issuecomment-1281406756)).

**Comment by rahim** [comment]
I've pushed a beta release that I hope should address the custom domain issue (#38) along with adding support for providing a secret. To opt in to the beta channel please follow [Google's instructions here](https://support.google.com/googleplay/answer/7003180). Please let me know how you get on and I'll promote to general release.

**Comment by rahim** [comment]
If you need it, the NightWear play store URL is https://play.google.com/store/apps/details?id=im.rah.nightwear

**Comment by rahim** [comment]
Better still from a web browser a direct link to join the beta - https://play.google.com/apps/testing/im.rah.nightwear
